### ISSUE TITLE
microstack defaults incompatible with virtualbox

### ISSUE THREAD

**Issue by mihalis68** [CanonicalLtd/microstack#41]
Microstack launches on an Ubuntu 18.04.1 LTS VM built on VirtualBox on a Mac, but is then incapable of launching an instance. 

The fix (for now) is to change /var/snap/microstack/common/etc/nova/nova.conf.d/hypervisor.conf to read

```
[libvirt]
virt_type = qemu
cpu_mode = host-model
```

and then
```
systemctl restart snap.microstack.nova-compute.service 
```
and then it works.

**Comment by petevg** [comment]
Thank you for the bug report + thorough documentation.

microstack is meant to drop in and work on as many host configurations as possible, regardless of the underlying metal or os. I think that we'd ideally add some automagic to setup an appropriate hypervisor.conf. Failing that, we should at least add a config hook that edits the file, for people not familiar with the underlying .conf files.

**Comment by petevg** [comment]
Merged to master. Release to edge backing right now ...
