### ISSUE TITLE
Openvswitch timeout when uninstalling/reinstalling

### ISSUE THREAD

**Issue by petevg** [CanonicalLtd/microstack#42]
When I uninstall a snap, then reinstall without a reboot, on a Thinkpad T480 running Ubuntu 18.10, I tend to get openvswitch timeouts when running snap install.

The error messages are not consistent -- it seems that there are multiple issues. I believe that openvswitch leaves a bit of a mess in memory.

This bug will be fixed when we can uninstall and reinstall smoothly, without a reboot in the middle, probably due to some tweaks to make openvswitch clean up more neatly.

**Comment by mborho** [comment]
The same happens for me, but after disabling and enabling the snap again. 
On ubuntu bionic. Sometimes more than one reboot is needed.

**Comment by petevg** [comment]
It looks like most of this was just as service ordering issue. If the openvswitch server started before the daemon was up, it could take a while to figure itself out, and timeout.

PR here: https://github.com/CanonicalLtd/microstack/pull/43/files

**Comment by petevg** [comment]
This is fixed in master, and I pushed the fix to edge. I think that we can close this issue!
