### ISSUE TITLE
microstack console error 

### ISSUE THREAD

**Issue by ghost** [CanonicalLtd/microstack#83]
Hello, I installed a microstack in Ubuntu with a plan to operate a vm. And now I'm going to upload another image, and then I'm going to set up a guitar setting, and I'm going to go into the console and check, but the connection was denied. has been marked. So I went around the internet and I went to nova .conf.d.

"nova.conf"
[vnc]
enabled = True
noovncproxy_base_url = http://IP_ADDRESS:6082/vnc_auto.html
server_listen = 127.0.0.1
server_proxyclient_address = 127.0.0.1
keymap = en-us
*I won't expose my lip.

"nova-novncproxy.conf"
[vnc]
novncproxy_host = 0.0.0.0
noovncproxy_port = 6082
to store and make sure it's working.
sudo systemctl restart snap.microstack*
I rewrote it through and came back into the console again, and it's not connected.

I don't know what I've been doing, but I've got a lot of your notes.

Currently, the microstek is set to console.
And ip is set to 12**.1**.***.149

**Comment by pengale** [comment]
Discussion for this currently lives here: https://bugs.launchpad.net/microstack/+bug/1812417

(Summary for posterity: the console doesn't currently work in MicroStack. We've got some work on roadmap to fix that.)
